### ISSUE TITLE
No support for Python3

### ISSUE THREAD

**Issue by mahirjain25** [atif93/google_image_downloader#3]
The current script uses urllib2, which is outdated and not supported by Python3. Further, instructions to install dependencies such as Geckodriver are not given. An alternate script for Python3 users will be very useful.

**Comment by phanirithvij** [comment]
Try [this](https://github.com/vivithemage/mrisa) one.
It has python3 support but I never tried using this google_image_downloader

**Comment by madhav1ag** [comment]
You can use 'urllib' instead of 'urllib2' for python3. Also make few changes 
`urllib.request.Request(img_url, headers=headers)`
`urllib.request.urlopen(req).read()`

Also don't forget to use ( ) with every print statement.

**Comment by mahirjain25** [comment]
Apologies for the delay. I shall look into it and make changes :)

**Comment by atif93** [comment]
The support has been added as part of https://github.com/atif93/google_image_downloader/pull/4, thanks to @mahirjain25!
